author: Gabriel Caelestis
email: gabriel@caelestis.one
description: profissional de segurança ofensiva e programador C/C++ com 15 anos de experiência prática

subtitle:
  typing:
    enable: true
    strings:
      - Ethical Hacker
      - AI Engineer
      - C/C++ developer
      - Sumerian enthusiast
    typeSpeed: 100               
    backSpeed: 50               
    backDelay: 2000            
    startDelay: 300           
    loop: true                   
    shuffle: true              
    showCursor: true            
    cursorChar: "|"             
    smartBackspace: false      

preloader:
  enable: true
  text:
    zh-CN: 少女祈祷中...
    zh-TW: 少女祈禱中...
    en: Carregando...
    ja: 少女祈祷中...
  icon: images/loading.png
  rotate: true

banner: "images/babylon.jpg"
excerpt_link: Read More

sidebar:
  position: left # left | right | false
  menu: false # whether to show the sidebar menu button, ignored on mobile devices
  article:
    show_common: true # whether to show common sidebar on article pages, ignored on mobile devices

show_update_time: true

clipboard:
  success: 
    en: Copy successfully (*^▽^*)
    zh-CN: 复制成功 (*^▽^*)
    zh-TW: 複製成功 (*^▽^*)
    ja: コピー成功 (*^▽^*)
    pt-BR: Copiado com sucesso (*^▽^*)
  fail: 
    en: Copy failed (ﾟ⊿ﾟ)ﾂ
    zh-CN: 复制失败 (ﾟ⊿ﾟ)ﾂ
    zh-TW: 複製失敗 (ﾟ⊿ﾟ)ﾂ
    ja: コピー失敗 (ﾟ⊿ﾟ)ﾂ
    pt-BR: Falha ao copiar (ﾟ⊿ﾟ)ﾂ
  copyright:
    enable: false
    count: 50 # The number of characters when the copyright is displayed
    license_type: by-nc-sa # https://creativecommons.org/licenses
    
social:
  - name: github
    url: https://github.com/rahvax
  - name: twitter
    url: https://www.x.com/rahvax
  - name: email
    url: mailto:gabriel@caelestis.one
  - name: youtube
    url: https://www.youtube.com/@GabrielCaelestis
  - name: telegram
    url: https://www.t.me/rahvax
  - name: steam
    url: https://steamcommunity.com/id/rahvax

footer:
  since: 2026 # The starting year displayed in the copyright information (e.g., 2020-current year)
  powered: false # Whether to display copyright information
  count: false # Whether to display word count and reading time statistics
  busuanzi: false # Whether to enable Busuanzi visitor counting statistics

rss:
  limit: 10 # The number of recent articles to be output, write -1 to output all
  showFullContent: false # output full content or description
  showCopyright: false # If true, add copyright to the end of article.

reimu_cursor: false

outdate:
  enable: true
  daysAgo: 180 # How many days old before an article is considered outdated
  message:
    en: Este artigo foi atualizado pela última vez em {time}. Considere a data ao ler o mesmo.
    zh-CN: 本文最后更新于 {time}，请注意文中内容可能已不适用。
    zh-TW: 本文最後更新於 {time}，請注意文中內容可能已不適用。
    ja: この記事は最終更新日：{time}。記載内容が現在有効でない可能性がありますのでご注意ください。

triangle_badge:
  enable: true
  icon: github 
  link: https://github.com/rahvax/site

menu:
  - name: home
    url: /
    icon: images/button.png
  - name: archives
    url: /archives
    icon: images/button.png # You can fill in a hexadecimal number to customize the icon. If set to false, no icon will be displayed.
  - name: about
    url: /about
    icon: images/button.png
  - name: friend
    url: /friend
    icon: images/button.png