baseURL: "https://www.caelestis.one/"
languageCode: "pt-br"
title: "Gabriel Caelestis"

theme: "ananke"

menu:
  main:
    - name: "Início"
      url: "/"
      weight: 1

    - name: "Blog"
      url: "/blog/"
      weight: 2

    - name: "Currículo"
      url: "/curriculo/"
      weight: 3

    - name: "Contato"
      url: "/contato/"
      weight: 4